[libraries]

lib7.files = [
    'decoder.vhd'
]

lib6.files = [
    'arithmetic/adder_sub.vhd'
]

lib5.files = [
    'reg.vhd'
]

lib4.files = [
    'counter.vhd' 
]

lib3.files = [
    'ram256x8.vhd'
]

lib2.files = [
    'logic_unit.vhd'
]

lib1.files = [
    'alu.vhd'
]