[libraries]

lib14.files = [
    'cpu.vhd'
]

lib15.files = [
    'control_unit/output_unit.vhd'
]

lib12.files = [
    'control_unit/mux4to1b.vhd'
]

lib11.files = [
    'memory/ram256x8.vhd'
]

lib10.files = [
    'memory/reg1bit.vhd'
]

lib9.files = [
    'control_unit/mux2to1.vhd'
]

lib8.files = [
    'control_unit/mux4to1.vhd'
]

lib7.files = [
    'control_unit/pc.vhd'
]

lib6.files = [
    'control_unit/control_unit.vhd'
]

lib5.files = [
    'control_unit/decoder.vhd'
]

lib4.files = [
    'memory/reg.vhd'
]

lib2.files = [
    'arithmetic/adder_sub.vhd'
]

lib1.files = [
    'arithmetic/alu.vhd'
]